<a href="https://colab.research.google.com/github/glgunderson/AI-Perceptions/blob/main/ai_perceptions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -O AI-111.xlsx "https://raw.githubusercontent.com/glgunderson/AI-Perceptions/main/data/AI-111.xlsx"

--2026-03-19 06:00:55--  https://raw.githubusercontent.com/glgunderson/AI-Perceptions/main/data/AI-111.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28471 (28K) [application/octet-stream]
Saving to: ‘AI-111.xlsx’

AI-111.xlsx         100%[===================>]  27.80K  --.-KB/s    in 0.002s

2026-03-19 06:00:55 (16.3 MB/s) - ‘AI-111.xlsx’ saved [28471/28471]

In [ ]:
import pandas as pd
df = pd.read_excel("AI-111.xlsx")
df.head()

,Age,Education,Frequency,Job status,Field,Field_10_TEXT,Perceptions_1,Perceptions_2,Perceptions_3,Perceptions_4,...,Procedural Fairness_2,Outcome Fairness_1,Outcome Fairness_2,Outcome Fairness_3,Performance Pressure_1,Performance Pressure_2,Performance Pressure_3,Competency_1,Competency_2,Competency_3
0,29,1,5,5,1,NaN,5,4,4,4,...,4,1,5,1,4,4,4,2,5,5
1,20,1,2,1,"7,8,9",NaN,4,3,3,3,...,4,3,3,2,4,2,3,2,2,3
2,20,1,4,5,"1,2,3,4,9",NaN,4,4,4,4,...,3,2,2,3,4,4,4,4,4,4
3,23,3,5,1,"1,4",NaN,4,4,4,5,...,3,2,4,3,4,4,4,4,4,5
4,20,1,3,5,"1,2,3,4,9",NaN,4,4,4,4,...,4,4,4,4,4,4,2,4,4,4

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 49 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Age                                                 110 non-null    int64
 1   Education                                           110 non-null    int64
 2   Frequency                                           110 non-null    int64
 3   Job status                                          110 non-null    int64
 4   Field                                               110 non-null    object
 5   Field_10_TEXT                                       7 non-null      object
 6   Perceptions_1                                       110 non-null    int64
 7   Perceptions_2                                       110 non-null    int64
 8   Perceptions_3                                       110 non-null    int64
 9   Perceptions_4                                       110 non-null    int64
 10  Perceptions_5                                       110 non-null    int64
 11  AI Expectations_1                                   110 non-null    int64
 12  AI Expectations_2                                   110 non-null    int64
 13  AI Expectations_3                                   110 non-null    int64
 14  AI Expectations_4                                   110 non-null    int64
 15  AI Expectations_5                                   110 non-null    int64
 16  AI Expectations_6                                   110 non-null    int64
 17  Resumes_1                                           110 non-null    int64
 18  Resumes_2                                           110 non-null    int64
 19  Resumes_3                                           110 non-null    int64
 20  Resumes_4                                           110 non-null    int64
 21  Recruitment_1                                       110 non-null    int64
 22  Recruitment_2                                       110 non-null    int64
 23  Recruitment_3                                       110 non-null    int64
 24  Recruitment_4                                       110 non-null    int64
 25  Recruitment_5                                       110 non-null    int64
 26  Recruitment_6                                       110 non-null    int64
 27  In your opinion, should AI be used in recruitment?  110 non-null    int64
 28  Fairness_1                                          110 non-null    int64
 29  Fairness_2                                          110 non-null    int64
 30  Fairness_3                                          110 non-null    int64
 31  Transparency _1                                     110 non-null    int64
 32  Transparency _2                                     110 non-null    int64
 33  Transparency _3                                     110 non-null    int64
 34  Usefulness_1                                        110 non-null    int64
 35  Usefulness_2                                        110 non-null    int64
 36  Usefulness_3                                        110 non-null    int64
 37  Willingness_1                                       110 non-null    int64
 38  Procedural Fairness_1                               110 non-null    int64
 39  Procedural Fairness_2                               110 non-null    int64
 40  Outcome Fairness_1                                  110 non-null    int64
 41  Outcome Fairness_2                                  110 non-null    int64
 42  Outcome Fairness_3                                  110 non-null    int64
 43  Performance Pressure_1                              110 non-null    int64
 44  Performance Pressure_2                              110 non-null    int64
 45  Performance Pressure_3                              110 non-null    int64
 46  Competency_1                                        110 non-null    int64
 47  Competency_2                                        110 non-null    int64
 48  Competency_3                                        110 non-null    int64
dtypes: int64(47), object(2)
memory usage: 42.2+ KB

,Age,Education,Frequency,Job status,Perceptions_1,Perceptions_2,Perceptions_3,Perceptions_4,Perceptions_5,AI Expectations_1,...,Procedural Fairness_2,Outcome Fairness_1,Outcome Fairness_2,Outcome Fairness_3,Performance Pressure_1,Performance Pressure_2,Performance Pressure_3,Competency_1,Competency_2,Competency_3
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,...,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,22.527273,1.372727,3.927273,2.536364,3.890909,3.754545,3.618182,4.172727,4.463636,4.081818,...,3.554545,2.572727,3.890909,2.454545,3.854545,3.872727,3.836364,3.909091,3.809091,3.881818
std,3.161434,0.647636,1.037897,1.769659,0.860397,0.869318,0.928467,0.822383,0.569521,0.791373,...,0.711458,1.035685,0.870995,1.001250,0.833214,0.847112,0.923965,0.883544,0.990741,0.786723
min,19.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,...,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,1.000000,3.000000,1.000000,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,...,3.000000,2.000000,3.250000,2.000000,3.250000,4.000000,3.000000,4.000000,3.000000,4.000000
50%,21.500000,1.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.500000,4.000000,...,4.000000,2.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,23.000000,2.000000,5.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,...,4.000000,3.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,37.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
!pip install pingouin

Requirement already satisfied: pingouin in /usr/local/lib/python3.12/dist-packages (0.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from pingouin) (3.10.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.12/dist-packages (from pingouin) (2.0.2)
Requirement already satisfied: pandas>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from pingouin) (2.2.2)
Requirement already satisfied: pandas_flavor in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.8.1)
Requirement already satisfied: scikit-learn>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from pingouin) (1.6.1)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from pingouin) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.13.2)
Requirement already satisfied: statsmodels>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.14.6)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from pingouin) (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->pingouin) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->pingouin) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1.1->pingouin) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.2->pingouin) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.2->pingouin) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.1->pingouin) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.14.1->pingouin) (26.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pingouin) (3.3.2)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from pandas_flavor->pingouin) (2025.12.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.1.1->pingouin) (1.17.0)

In [ ]:
PP = df[['Performance Pressure_1', 'Performance Pressure_2', 'Performance Pressure_3']]
CE = df[['Competency_1', 'Competency_2', 'Competency_3']]

In [ ]:
import pingouin as pg

pg.cronbach_alpha(PP)
pg.cronbach_alpha(CE)

(np.float64(0.6895957913859663), array([0.574, 0.778]))

Cronbach’s alpha for the Performance Pressure (PP) scale was 0.69, indicating marginal internal consistency. While close to the commonly accepted threshold of 0.70, the relatively wide confidence interval suggests variability in item coherence.

In [ ]:
PP12 = df[['Performance Pressure_1', 'Performance Pressure_2']]
CE12 = df[['Competency_1', 'Competency_2']]

pg.cronbach_alpha(PP12)
pg.cronbach_alpha(CE12)

(np.float64(0.7119997561644671), array([0.58 , 0.803]))

The Performance Pressure scale demonstrated marginal internal consistency (α = 0.69). Item-level analysis indicated that the third item exhibited weaker alignment with the other indicators, suggesting some variation in how different dimensions of performance expectations are perceived.

*AI may increase different types of pressure, not one single dimension.*

In [ ]:
PP13 = df[['Performance Pressure_1', 'Performance Pressure_3']]
CE13 = df[['Competency_1', 'Competency_3']]


pg.cronbach_alpha(PP13)
pg.cronbach_alpha(CE13)

(np.float64(0.46052933351681125), array([0.213, 0.63 ]))

In [ ]:
PP23 = df[['Performance Pressure_2', 'Performance Pressure_3']]
CE23 = df[['Competency_2', 'Competency_3']]


pg.cronbach_alpha(PP23)
pg.cronbach_alpha(CE23)

(np.float64(0.5670549581839905), array([0.369, 0.703]))

In [ ]:
df['PP_score'] = PP.mean(axis=1)
df['CE_score'] = CE.mean(axis=1)

In [ ]:
df[['PP_score', 'CE_score']].describe()

         PP_score    CE_score
count  110.000000  110.000000
mean     3.854545    3.866667
std      0.745393    0.699789
min      1.666667    1.666667
25%      3.666667    3.666667
50%      4.000000    4.000000
75%      4.333333    4.333333
max      5.000000    5.000000

In [ ]:
df[['PP_score', 'CE_score']].corr()

          PP_score  CE_score
PP_score   1.00000   0.55266
CE_score   0.55266   1.00000

In [ ]:
IV5 = df[['Perceptions_1','Perceptions_2','Perceptions_3','Perceptions_4','Perceptions_5']]
df['IV5_score'] = IV5.mean(axis=1)

pg.cronbach_alpha(IV5)

(np.float64(0.5709304051046149), array([0.43 , 0.686]))

## Construct Refinement

In [ ]:
IV345 = df[['Perceptions_3','Perceptions_4','Perceptions_5']]
df['IV345_score'] = IV345.mean(axis=1)

pg.cronbach_alpha(IV345)

(np.float64(0.5959358808290156), array([0.445, 0.711]))

In [ ]:
IV = df[['Perceptions_4','Perceptions_5']]
df['IV_score'] = IV.mean(axis=1)

pg.cronbach_alpha(IV)

(np.float64(0.7276776246023335), array([0.603, 0.813]))

Perceived AI integration was operationalized using two items reflecting the increasing prevalence and future dominance of AI in the workplace. These items demonstrated acceptable internal consistency (α = 0.73).