<a href="https://colab.research.google.com/github/glgunderson/AI-Perceptions/blob/main/AI_Perceptions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
!wget -O AI-111.xlsx "https://raw.githubusercontent.com/glgunderson/AI-Perceptions/main/data/AI-111.xlsx"

--2026-03-19 05:28:26--  https://raw.githubusercontent.com/glgunderson/AI-Perceptions/main/data/AI-111.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28471 (28K) [application/octet-stream]
Saving to: ‘AI-111.xlsx’

AI-111.xlsx         100%[===================>]  27.80K  --.-KB/s    in 0.002s

2026-03-19 05:28:26 (15.3 MB/s) - ‘AI-111.xlsx’ saved [28471/28471]

In [25]:
import pandas as pd
df = pd.read_excel("AI-111.xlsx")
df.head()

,Age,Education,Frequency,Job status,Field,Field_10_TEXT,Perceptions_1,Perceptions_2,Perceptions_3,Perceptions_4,...,Procedural Fairness_2,Outcome Fairness_1,Outcome Fairness_2,Outcome Fairness_3,Performance Pressure_1,Performance Pressure_2,Performance Pressure_3,Competency_1,Competency_2,Competency_3
0,29,1,5,5,1,NaN,5,4,4,4,...,4,1,5,1,4,4,4,2,5,5
1,20,1,2,1,"7,8,9",NaN,4,3,3,3,...,4,3,3,2,4,2,3,2,2,3
2,20,1,4,5,"1,2,3,4,9",NaN,4,4,4,4,...,3,2,2,3,4,4,4,4,4,4
3,23,3,5,1,"1,4",NaN,4,4,4,5,...,3,2,4,3,4,4,4,4,4,5
4,20,1,3,5,"1,2,3,4,9",NaN,4,4,4,4,...,4,4,4,4,4,4,2,4,4,4

In [26]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 49 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Age                                                 110 non-null    int64
 1   Education                                           110 non-null    int64
 2   Frequency                                           110 non-null    int64
 3   Job status                                          110 non-null    int64
 4   Field                                               110 non-null    object
 5   Field_10_TEXT                                       7 non-null      object
 6   Perceptions_1                                       110 non-null    int64
 7   Perceptions_2                                       110 non-null    int64
 8   Perceptions_3                                       110 non-null    int64
 9   Perceptions_4                                       110 non-null    int64
 10  Perceptions_5                                       110 non-null    int64
 11  AI Expectations_1                                   110 non-null    int64
 12  AI Expectations_2                                   110 non-null    int64
 13  AI Expectations_3                                   110 non-null    int64
 14  AI Expectations_4                                   110 non-null    int64
 15  AI Expectations_5                                   110 non-null    int64
 16  AI Expectations_6                                   110 non-null    int64
 17  Resumes_1                                           110 non-null    int64
 18  Resumes_2                                           110 non-null    int64
 19  Resumes_3                                           110 non-null    int64
 20  Resumes_4                                           110 non-null    int64
 21  Recruitment_1                                       110 non-null    int64
 22  Recruitment_2                                       110 non-null    int64
 23  Recruitment_3                                       110 non-null    int64
 24  Recruitment_4                                       110 non-null    int64
 25  Recruitment_5                                       110 non-null    int64
 26  Recruitment_6                                       110 non-null    int64
 27  In your opinion, should AI be used in recruitment?  110 non-null    int64
 28  Fairness_1                                          110 non-null    int64
 29  Fairness_2                                          110 non-null    int64
 30  Fairness_3                                          110 non-null    int64
 31  Transparency _1                                     110 non-null    int64
 32  Transparency _2                                     110 non-null    int64
 33  Transparency _3                                     110 non-null    int64
 34  Usefulness_1                                        110 non-null    int64
 35  Usefulness_2                                        110 non-null    int64
 36  Usefulness_3                                        110 non-null    int64
 37  Willingness_1                                       110 non-null    int64
 38  Procedural Fairness_1                               110 non-null    int64
 39  Procedural Fairness_2                               110 non-null    int64
 40  Outcome Fairness_1                                  110 non-null    int64
 41  Outcome Fairness_2                                  110 non-null    int64
 42  Outcome Fairness_3                                  110 non-null    int64
 43  Performance Pressure_1                              110 non-null    int64
 44  Performance Pressure_2                              110 non-null    int64
 45  Performance Pressure_3                              110 non-null    int64
 46  Competency_1                                        110 non-null    int64
 47  Competency_2                                        110 non-null    int64
 48  Competency_3                                        110 non-null    int64
dtypes: int64(47), object(2)
memory usage: 42.2+ KB

,Age,Education,Frequency,Job status,Perceptions_1,Perceptions_2,Perceptions_3,Perceptions_4,Perceptions_5,AI Expectations_1,...,Procedural Fairness_2,Outcome Fairness_1,Outcome Fairness_2,Outcome Fairness_3,Performance Pressure_1,Performance Pressure_2,Performance Pressure_3,Competency_1,Competency_2,Competency_3
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,...,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,22.527273,1.372727,3.927273,2.536364,3.890909,3.754545,3.618182,4.172727,4.463636,4.081818,...,3.554545,2.572727,3.890909,2.454545,3.854545,3.872727,3.836364,3.909091,3.809091,3.881818
std,3.161434,0.647636,1.037897,1.769659,0.860397,0.869318,0.928467,0.822383,0.569521,0.791373,...,0.711458,1.035685,0.870995,1.001250,0.833214,0.847112,0.923965,0.883544,0.990741,0.786723
min,19.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,...,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000
25%,21.000000,1.000000,3.000000,1.000000,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,...,3.000000,2.000000,3.250000,2.000000,3.250000,4.000000,3.000000,4.000000,3.000000,4.000000
50%,21.500000,1.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.500000,4.000000,...,4.000000,2.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,23.000000,2.000000,5.000000,5.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,...,4.000000,3.000000,4.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000
max,37.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000